using RevitCommandLine.UI.CommandLine.Models;
using System.Collections.ObjectModel;

namespace RevitCommandLine.UI.CommandLine.Commands;
internal class StandardCommandsList
{
    public StandardCommandsList(ref ObservableCollection<CommandItem> commandItems)
    {
        //-----------Architecture
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ArchitecturalWall", Description = "Architecture → Build → Wall → Wall: Architectural" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "StructuralWall", Description = "Architecture → Build → Wall → Wall: Structural" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "WallByFaceWall", Description = "Architecture → Build → Wall → Wall by Face" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "SweepWall", Description = "Architecture → Build → Wall → Wall: Sweep" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "RevealWall", Description = "Architecture → Build → Wall → Wall: Reveal" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Door", Description = "Architecture → Build → Door" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Window", Description = "Architecture → Build → Window" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "PlaceAComponent", Description = "Architecture → Build  → Component → Place a Component" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ModelInPlace", Description = "Architecture → Build  → Component → Model In-Place" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "StructuralColumn", Description = "Architecture → Build → Column → Structural Column" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ArchitecturalColumn", Description = "Architecture → Build → Column → Column: Architectural" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "RoofByFootprint", Description = "Architecture → Build → Roof → Roof by Footprint" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "RoofByExtrusion", Description = "Architecture → Build → Roof → Roof by Extrusion" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "RoofByFace", Description = "Architecture → Build → Roof → Roof by Face" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "AutomaticCeiling", Description = "Architecture → Build → Ceiling" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ArchitecturalFloor", Description = "Architecture → Build → Floor → Floor: Architectural" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "StructuralFloor", Description = "Architecture → Build → Floor → Floor: Structural" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "FloorByFaceFloor", Description = "Architecture → Build → Floor → Floor by Face" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "SlabEdgeFloor", Description = "Architecture → Build → Floor → Floor: Slab Edge" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "CurtainSystemByFace", Description = "Architecture → Build → Curtain System" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "CurtainGrid", Description = "Architecture → Build → Curtain Grid" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "CurtainWallMullion", Description = "Architecture → Build → Curtain Mullion" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Railing", Description = "Architecture → Circulation → Railing → Scetch Path" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "PlaceOnStairOrRamp", Description = "Architecture → Circulation → Railing → Place on Stair/Ramp" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Ramp", Description = "Architecture → Circulation → Ramp" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Stair", Description = "Architecture → Circulation → Stair" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ModelText", Description = "Architecture → Model → ModelText" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ModelLine", Description = "Architecture → Model → ModelLine" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "PlaceDetailGroup", Description = "Architecture → Model → Model Group → Place Model Group" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "CreateGroup", Description = "Architecture → Model → Model Group → Create Group" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "LoadAsGroup", Description = "Architecture → Model → Model Group → Load as Group into Open Projects" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Room", Description = "Architecture → Room & Area → Room" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "RoomSeparator", Description = "Architecture → Room & Area → Room Separator" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "RoomTag", Description = "Architecture → Room & Area → Tag Room" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "TagAllNotTagged", Description = "Architecture → Room & Area → Tag All Not Tagged" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "AreaPlan", Description = "Architecture → Room & Area → Area → Area Plan" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "AreaBoundary", Description = "Architecture → Room & Area → Area → Area Boundary" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "OpeningByFace", Description = "Architecture → Opening → By Face" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ShaftOpening", Description = "Architecture → Opening → Shaft" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "WallOpening", Description = "Architecture → Opening → Wall" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "VerticalOpening", Description = "Architecture → Opening → Vertical" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "DormerOpening", Description = "Architecture → Opening → Dormer" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Level", Description = "Architecture → Datum → Level" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Grid", Description = "Architecture → Datum → Grid" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "SetWorkPlane", Description = "Architecture → Work Plane → Set → Set Work Plane" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "PickAPlane", Description = "Architecture → Work Plane → Set → Pick a Plane" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ShowWorkPlane", Description = "Architecture → Work Plane → Show" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ReferencePlane", Description = "Architecture → Work Plane → Ref Plane" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "FormWorkPlaneView", Description = "Architecture → Work Plane → Viewer" });

        //-----------Structure
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Beam", Description = "Structure → Structure → Beam" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "StructuralTrusses", Description = "Structure → Structure → StructuralTrusses" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Brace", Description = "Structure → Structure → Brace" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "AutomaticBeamSystem", Description = "Structure → Structure → Beam System" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "StructuralConnection", Description = "Structure → Connection → Connection" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Isolated", Description = "Structure → Foundation → Isolated" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Wall", Description = "Structure → Foundation → Wall" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Slab", Description = "Structure → Foundation → Slab → Structural Foundation: Slab" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "SlabEdgeFloor", Description = "Structure → Foundation → Slab → Floor: Slab Edge" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "StructuralRebar", Description = "Structure → Reinforcement → Rebar" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Area", Description = "Structure → Reinforcement → Area" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "StructuralPathReinforcement", Description = "Structure → Reinforcement → Path" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "StructuralFabricArea", Description = "Structure → Reinforcement → Fabric Area" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "SingleFabricSheetPlacement", Description = "Structure → Reinforcement → Fabric Sheet" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "EditRebarCover", Description = "Structure → Reinforcement → Cover" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "InsertCoupler", Description = "Structure → Reinforcement → Rebar Coupler" });

        //-----------Steel
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Plate", Description = "Steel → Fabrication Elements → Plate" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Bolts", Description = "Steel → Fabrication Elements → Bolts → Bolts" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Anchors", Description = "Steel → Fabrication Elements → Bolts → Anchors" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Holes", Description = "Steel → Fabrication Elements → Bolts → Holes" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ShearStuds", Description = "Steel → Fabrication Elements → Bolts → Shear Studs" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Welds", Description = "Steel → Fabrication Elements → Welds" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "CornerCut", Description = "Steel → Modifiers → Corner Cut" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "CopeSkewed", Description = "Steel → Modifiers → Notch Skewed" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Shorten", Description = "Steel → Modifiers → Shorten" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ContourCut", Description = "Steel → Modifiers → Contour Cut" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Cope", Description = "Steel → Parametric Cuts → Notch" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Miter", Description = "Steel → Parametric Cuts → Miter → Miter" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "SawCutFlange", Description = "Steel → Parametric Cuts → Miter → Saw cut - Flange" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "SawCutWeb", Description = "Steel → Parametric Cuts → Miter → Saw cut - Web" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "CutThrough", Description = "Steel → Parametric Cuts → Cut Through" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "CutBy", Description = "Steel → Parametric Cuts → Cut By" });

        //----------Systems
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Duct", Description = "Systems → HVAC → Duct" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "DuctPlaceholder", Description = "Systems → HVAC → Duct Placeholder" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "DuctFitting", Description = "Systems → HVAC → Duct Fitting" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "DuctAccessory", Description = "Systems → HVAC → Duct Accessory" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ConvertToFlexDuct", Description = "Systems → HVAC → Convert to Flex Duct" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "FlexDuct", Description = "Systems → HVAC → Flex Duct" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "AirTerminal", Description = "Systems → HVAC → Air Terminal" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "FabricationPart", Description = "Systems → Fabrication → Fabrication Part" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "MultiPointRouting", Description = "Systems → Fabrication → Multi-Point Routing" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "MEPFabricationDuctworkStiffener", Description = "Systems → MEP Detailing → MEP Fabrication Ductwork Stiffener" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "PAndIDModeler", Description = "Systems → P&ID Collaboration → P&ID Modeler" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "MechanicalEquipment", Description = "Systems → Mechanical → Mechanical Equipment" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "MechanicalControlDevice", Description = "Systems → Mechanical → Mechanical Control Device" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Pipe", Description = "Systems → Plumbing & Piping → Pipe" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "PipePlaceholder", Description = "Systems → Plumbing & Piping → Pipe Placeholder" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ParallelPipes", Description = "Systems → Plumbing & Piping → Parallel Pipes" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "PipeFitting", Description = "Systems → Plumbing & Piping → Pipe Fitting" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "PipeAccessory", Description = "Systems → Plumbing & Piping → Pipe Accessory" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "FlexPipe", Description = "Systems → Plumbing & Piping → Flex Pipe" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "PlumbingEquipment", Description = "Systems → Plumbing & Piping → Plumbing Equipment" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "PlumbingFixture", Description = "Systems → Plumbing & Piping → Plumbing Fixture" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Sprinkler", Description = "Systems → Plumbing & Piping → Sprinkler" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ArcWire", Description = "Systems → Electrical → Wire" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "CableTray", Description = "Systems → Electrical → Cable Tray" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Conduit", Description = "Systems → Electrical → Conduit" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ParallelConduits", Description = "Systems → Electrical → Parallel Conduits" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "CableTrayFitting", Description = "Systems → Electrical → Cable Tray Fitting" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ElectricalEquipment", Description = "Systems → Electrical → Electrical Equipment" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ElectricalFixture", Description = "Systems → Electrical → Device → Electrical Fixture" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Communication", Description = "Systems → Electrical → Device → Communication" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Data", Description = "Systems → Electrical → Device → Data" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "FireAlarm", Description = "Systems → Electrical → Device → Fire Alarm" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Lighting", Description = "Systems → Electrical → Device → Lighting" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "NurseCall", Description = "Systems → Electrical → Device → Nurse Call" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Security", Description = "Systems → Electrical → Device → Security" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Telephone", Description = "Systems → Electrical → Device → Telephone" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "LightingFixture", Description = "Systems → Electrical → Lighting Fixture" });

        //-----------Insert
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "LinkRevit", Description = "Insert → Link → Link Revit" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "LinkIFC", Description = "Insert → Link → Link IFC" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "LinkCAD", Description = "Insert → Link → Link CAD" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "LinkTopography", Description = "Insert → Link → Link Topography" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "DWFMarkup", Description = "Insert → Link → DWF Markup" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "PlaceDecal", Description = "Insert → Link → Decal → Place Decal" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "DecalTypes", Description = "Insert → Link → Decal → Decal Types" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "PointCloud", Description = "Insert → Link → Point Cloud" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "CoordinationModelLocal", Description = "Insert → Link → Coordination Model → Local" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "CoordinationModelAutodeskDocs", Description = "Insert → Link → Coordination Model → Autodesk Docs" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "LinkPDF", Description = "Insert → Link → Link PDF" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "LinkImage", Description = "Insert → Link → Link Image" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ManageLinks", Description = "Insert → Link → Manage Links" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ImportCAD", Description = "Insert → Import → Import CAD" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ImportGBXML", Description = "Insert → Import → Import gbXML" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ImportPDF", Description = "Insert → Import → Import PDF" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ImportImage", Description = "Insert → Import → Import Image" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "LoadFamilyIntoProjectAndClose", Description = "Insert → Load from Library → Load Family" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "LoadAutodeskFamily", Description = "Insert → Load from Library → Load Autodesk Family" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "InsertViewsFromFile", Description = "Insert → Load from Library → Insert from File → Insert Views from File" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Insert2DElementsFromFile", Description = "Insert → Load from Library → Insert from File → Insert 2D Elements from File" });

        //-----------Annotate
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "AlignedDimension", Description = "Annotate → Dimension → Aligned" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "LinearDimension", Description = "Annotate → Dimension → Linear" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "AngularDimension", Description = "Annotate → Dimension → Angular" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "RadialDimension", Description = "Annotate → Dimension → Radial" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ArcLengthDimension", Description = "Annotate → Dimension → Arc Length" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "SpotElevation", Description = "Annotate → Dimension → Spot Elevation" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "SpotCoordinate", Description = "Annotate → Dimension → Spot Coordinate" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "SpotSlope", Description = "Annotate → Dimension → Spot Slope" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "DetailLine", Description = "Annotate → Detail → Detail Line" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "FilledRegion", Description = "Annotate → Detail → Region → Filled Region" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "MaskingRegion", Description = "Annotate → Detail → Region → Masking Region" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "DetailComponent", Description = "Annotate → Detail → Component → Detail Component" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "RepeatingDetailComponent", Description = "Annotate → Detail → Component → Repeating Detail Component" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "LegendComponent", Description = "Annotate → Detail → Component → Legend Component" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "RevisionCloud", Description = "Annotate → Detail → Revision Cloud" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Insulation", Description = "Annotate → Detail → Insulation" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Text", Description = "Annotate → Text → Text" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "CheckSpelling", Description = "Annotate → Text → Check Spelling" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "FindOrReplace", Description = "Annotate → Text → Find/Replace" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "TagByCategory", Description = "Annotate → Tag → Tag by Category" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "TagAllNotTagged", Description = "Annotate → Tag → Tag All" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "BeamAnnotations", Description = "Annotate → Tag → Beam Annotations" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "MultiCategoryTag", Description = "Annotate → Tag → Multi-Category Tag" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "MaterialTag", Description = "Annotate → Tag → Material Tag" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "AreaTag", Description = "Annotate → Tag → Area Tag" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "RoomTag", Description = "Annotate → Tag → Room Tag" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ViewReference", Description = "Annotate → Tag → View Reference" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "StairTreadOrRiserNumber", Description = "Annotate → Tag → Tread Number" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "AlignedMultiRebarAnnotation", Description = "Annotate → Tag → Multi-Rebar → Aligned Multi-Rebar Annotation" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "LinearMultiRebarAnnotation", Description = "Annotate → Tag → Multi-Rebar → Linear Multi-Rebar Annotation" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ElementKeynote", Description = "Annotate → Tag → Keynote → Element Keynote" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "MaterialKeynote", Description = "Annotate → Tag → Keynote → Material Keynote" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "UserKeynote", Description = "Annotate → Tag → Keynote → User Keynote" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "KeynotingSettings", Description = "Annotate → Tag → Keynote → Keynoting Settings" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "DuctLegend", Description = "Annotate → Color Fill → Duct Legend" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "PipeLegend", Description = "Annotate → Color Fill → Pipe Legend" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ColorFillLegend", Description = "Annotate → Color Fill → Color Fill Legend" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Symbol", Description = "Annotate → Symbol → Symbol" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "SpanDirectionSymbol", Description = "Annotate → Symbol → Span Direction" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "BeamSystemSymbol", Description = "Annotate → Symbol → Beam" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "StairPath", Description = "Annotate → Symbol → Stair Path" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "AreaReinforcementSymbol", Description = "Annotate → Symbol → Area" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "PathReinforcementSymbol", Description = "Annotate → Symbol → Path" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "RebarBendingDetail", Description = "Annotate → Symbol → Rebar" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "FabricReinforcementSymbol", Description = "Annotate → Symbol → Fabric" });

        //-----------View
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ApplyTemplatePropertiesToCurrentView", Description = "View → Graphics → View Templates → Apply Template Properties to Current View" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "CreateTemplateFromCurrentView", Description = "View → Graphics → View Templates → Create Template from Current View" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "VisibilityOrGraphics", Description = "View → Graphics → Visibility/Graphics" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Filters", Description = "View → Graphics → Filters" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ThinLines", Description = "View → Graphics → Thin Lines" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ShowHiddenLinesByElement", Description = "View → Graphics → Show Hidden Lines" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "RemoveHiddenLinesByElement", Description = "View → Graphics → Remove Hidden Lines" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "CutProfile", Description = "View → Graphics → Cut Profile" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Render", Description = "View → Presentation → Render" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "RenderInCloud", Description = "View → Presentation → Cloud Rendering → Render in Cloud" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "RenderGallery", Description = "View → Presentation → Cloud Rendering → Render Gallery" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Default3DView", Description = "View → Create → 3D View → Default 3D View" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Camera", Description = "View → Create → 3D View → Camera" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Walkthrough", Description = "View → Create → 3D View → Walkthrough" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Section", Description = "View → Create → Section" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Callout", Description = "View → Create → Callout → Rectangle" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "FloorPlan", Description = "View → Create → Plan Views → Floor Plan" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ReflectedCeilingPlan", Description = "View → Create → Plan Views → Reflected Ceiling Plan" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "StructuralPlan", Description = "View → Create → Plan Views → Structural Plan" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "PlanRegion", Description = "View → Create → Plan Views → Plan Region" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "AreaPlan", Description = "View → Create → Plan Views → Area Plan" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "BuildingElevation", Description = "View → Create → Elevation → Elevation" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "FramingElevation", Description = "View → Create → Elevation → Framing Elevation" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "DraftingView", Description = "View → Create → Drafting View" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "DuplicateView", Description = "View → Create → Duplicate View → Duplicate View" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "DuplicateWithDetailing", Description = "View → Create → Duplicate View → Duplicate With Detailing" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "DuplicateAsDependent", Description = "View → Create → Duplicate View → Duplicate As Dependent" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Legend", Description = "View → Create → Legends → Legend" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "KeynoteLegend", Description = "View → Create → Legends → Keynote Legend" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ScheduleOrQuantities", Description = "View → Create → Schedules → Schedule/Quantities" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "GraphicalColumnSchedule", Description = "View → Create → Schedules → Graphical Column Schedule" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "MaterialTakeoff", Description = "View → Create → Schedules → Material Takeoff" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "SheetList", Description = "View → Create → Schedules → Sheet List" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "NoteBlock", Description = "View → Create → Schedules → Note Block" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ViewList", Description = "View → Create → Schedules → View List" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ScopeBox", Description = "View → Create → Schedules → Scope Box" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "NewSheet", Description = "View → Sheet Composition → Sheet" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "PlaceView", Description = "View → Sheet Composition → View" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "TitleBlock", Description = "View → Sheet Composition → Title Block" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "SheetIssuesOrRevisions", Description = "View → Sheet Composition → Revisions" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "GuideGrid", Description = "View → Sheet Composition → Guide Grid" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Matchline", Description = "View → Sheet Composition → Matchline" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ViewReference", Description = "View → Sheet Composition → View Reference" });

        //-----------Modify
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Materials", Description = "Manage → Settings → Materials" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ObjectStyles", Description = "Manage → Settings → Object Styles" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Snaps", Description = "Manage → Settings → Snaps" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ProjectInformation", Description = "Manage → Settings → Project Information" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ParametersService", Description = "Manage → Settings → Parameters Service" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ProjectParameters", Description = "Manage → Settings → Project Parameters" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "SharedParameters", Description = "Manage → Settings → Shared Parameters" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "GlobalParameters", Description = "Manage → Settings → Global Parameters" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "TransferProjectStandards", Description = "Manage → Settings → Transfer Project Standards" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "PurgeUnused", Description = "Manage → Settings → Purge Unused" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ProjectUnits", Description = "Manage → Settings → Project Units" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "StructuralSettings", Description = "Manage → Settings → Structural Settings → Structural Settings" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ConnectionSettings", Description = "Manage → Settings → Structural Settings → Connection Settings" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "MechanicalSettings", Description = "Manage → Settings → MEP Settings → Mechanical Settings" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ElectricalSettings", Description = "Manage → Settings → MEP Settings → Electrical Settings" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "FabricationSettings", Description = "Manage → Settings → MEP Settings → Fabrication Settings" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "LoadClassifications", Description = "Manage → Settings → MEP Settings → Load Classifications" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "DemandFactors", Description = "Manage → Settings → MEP Settings → Demand Factors" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "BuildingOrSpaceTypeSettings", Description = "Manage → Settings → MEP Settings → Building/Space Type Settings" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ElectricalAnalyticalLoadTypeSettings", Description = "Manage → Settings → MEP Settings → Electrical Analytical Load Type Settings" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ManageTemplates", Description = "Manage → Settings → Panel Schedule Templates → Manage Templates" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "EditATemplate", Description = "Manage → Settings → Panel Schedule Templates → Edit a Template" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "LineStyles", Description = "Manage → Settings → Additional Settings → Line Styles" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "LineWeights", Description = "Manage → Settings → Additional Settings → Line Weights" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "LinePatterns", Description = "Manage → Settings → Additional Settings → Line Patterns" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "FillPatterns", Description = "Manage → Settings → Additional Settings → Fill Patterns" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Arrowheads", Description = "Manage → Settings → Additional Settings → Annotations → Arrowheads" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "TemporaryDimensions", Description = "Manage → Settings → Additional Settings → Annotations → Temporary Dimensions" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "SectionTags", Description = "Manage → Settings → Additional Settings → Annotations → Section Tags" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ElevationTags", Description = "Manage → Settings → Additional Settings → Annotations → Elevation Tags" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "CalloutTags", Description = "Manage → Settings → Additional Settings → Annotations → Callout Tags" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "HalftoneOrUnderlay", Description = "Manage → Settings → Additional Settings → Halftone/Underlay" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "SunSettings", Description = "Manage → Settings → Additional Settings → Sun Settings" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "MaterialAssets", Description = "Manage → Settings → Additional Settings → Material Assets" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "AnalysisDisplayStyles", Description = "Manage → Settings → Additional Settings → Analysis Display Styles" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "DetailLevel", Description = "Manage → Settings → Additional Settings → Detail Level" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "AssemblyCode", Description = "Manage → Settings → Additional Settings → Assembly Code" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "MultipleValuesIndication", Description = "Manage → Settings → Additional Settings → Multiple Values Indication" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "Location", Description = "Manage → Project Location → Location" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "AcquireCoordinates", Description = "Manage → Project Location → Coordinates → Acquire Coordinates" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "PublishCoordinates", Description = "Manage → Project Location → Coordinates → Publish Coordinates" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ResetSharedCoordinates", Description = "Manage → Project Location → Coordinates → Reset Shared Coordinates" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "SpecifyCoordinatesAtPoint", Description = "Manage → Project Location → Coordinates → Specify Coordinates at Point" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "ReportSharedCoordinates", Description = "Manage → Project Location → Coordinates → Report Shared Coordinates" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "RelocateProject", Description = "Manage → Project Location → Position → Relocate Project" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "RotateTrueNorth", Description = "Manage → Project Location → Position → Rotate True North" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "MirrorProject", Description = "Manage → Project Location → Position → Mirror Project" });
        commandItems.Add(new CommandItem() { CommandType = CommandType.Standard, PostableCommandName = "RotateProjectNorth", Description = "Manage → Project Location → Position → Rotate Project North" });
    }
}
